# Generated by Django 4.0.1 on 2022-05-31 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=b'I01\n', serialize=False, verbose_name='id categoria')),
                ('nombre_categoria', models.CharField(max_length=30, verbose_name='nombre categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=b'I01\n', serialize=False, verbose_name='id comuna')),
                ('nombre_comuna', models.CharField(max_length=25, verbose_name='nombre comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id_descuento', models.IntegerField(primary_key=b'I01\n', serialize=False, verbose_name='Id descuento')),
                ('porc_descuento', models.IntegerField(verbose_name='porcentaje descuento')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=b'I01\n', serialize=False, verbose_name='id producto')),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='nombre producto')),
                ('precio_producto', models.IntegerField(verbose_name='precio producto')),
                ('stock', models.IntegerField(verbose_name='stocks producto')),
                ('descripcion_producto', models.TextField(max_length=200, verbose_name='descripcion producto')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=b'I01\n', serialize=False, verbose_name='id region')),
                ('nombre_region', models.CharField(max_length=20, verbose_name='nombre region')),
            ],
        ),
        migrations.CreateModel(
            name='Terminos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nuevos_productos', models.IntegerField(verbose_name='id nuevos productos')),
                ('id_nov_ofertas', models.IntegerField(verbose_name='id novedades y ofertas')),
                ('si_no', models.CharField(max_length=2, verbose_name='opcion si o no')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=b'I01\n', serialize=False, verbose_name='Id de usuario')),
                ('nombre_usuario', models.CharField(max_length=30, verbose_name='Nombre Usuario')),
                ('contraseña_usuario', models.CharField(max_length=20, verbose_name='Contraseña Usuario')),
                ('email_usuario', models.EmailField(max_length=100, verbose_name='Correo electronico Usuario')),
                ('celular_usuario', models.IntegerField(verbose_name='Celular Usuario')),
                ('direccion_usuario', models.TextField(max_length=200, verbose_name='Direccion Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id_socio', models.IntegerField(primary_key=b'I01\n', serialize=False, verbose_name='Id Socio')),
                ('tipo_socio', models.CharField(max_length=10, verbose_name='Tipo de Socio')),
                ('donacion_socio', models.IntegerField(verbose_name='Donacion Socio')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario', verbose_name='Id Usuario')),
            ],
        ),
    ]
