# Generated by Django 4.0.4 on 2022-06-29 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categoria',
                'db_table': 'categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(max_length=200, verbose_name='Descripcion del Producto')),
                ('marca', models.CharField(max_length=50, null=True, verbose_name='Marca del Producto')),
                ('precio', models.IntegerField(verbose_name='Precio del Producto')),
                ('stock', models.IntegerField(verbose_name='Stock del Producto')),
                ('imagen', models.ImageField(upload_to='images/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Producto',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
    ]
