# Generated by Django 4.0.4 on 2022-06-03 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombre_categoria', models.CharField(max_length=50, verbose_name='Nombre de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre_producto', models.TextField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre del Producto')),
                ('descripcion_producto', models.TextField(max_length=200, verbose_name='Descripcion del Producto')),
                ('precio_producto', models.IntegerField(verbose_name='Precio del Producto')),
                ('stock_producto', models.IntegerField(verbose_name='Stock del Producto')),
                ('imagen_producto', models.ImageField(upload_to='img/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
