# Generated by Django 4.0.4 on 2022-06-05 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_imagen_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id_socio', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del socio')),
                ('pertenece_socio', models.CharField(max_length=3, verbose_name='Pertenece a socio SI/NO')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre_usuario', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre del Usuario')),
                ('email_usuario', models.CharField(max_length=100, verbose_name='Correo del Usuario')),
                ('contraseña_usuario', models.CharField(max_length=25, verbose_name='Contraseña del Usuario')),
                ('Socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.socio')),
            ],
        ),
    ]
