# Generated by Django 4.0.1 on 2022-06-03 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_imagen_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id_socio', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Socio')),
                ('pertenece', models.CharField(max_length=2, verbose_name='Pertenece si o no')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Usuario')),
                ('nombre_usuario', models.CharField(max_length=30, verbose_name='Nombre Usuario')),
                ('correo', models.EmailField(max_length=254, verbose_name='Email de Usuario')),
                ('contrasena', models.CharField(max_length=16, verbose_name='Contraseña Usuario')),
                ('direccion', models.TextField(max_length=50, verbose_name='Direccion Usuario')),
                ('celular', models.IntegerField(verbose_name='Celular Usuario')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.socio')),
            ],
        ),
    ]
