# Generated by Django 4.0.4 on 2022-06-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_socio_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre del Producto'),
        ),
    ]
