# Generated by Django 4.0.4 on 2022-06-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_producto_nombre_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca_producto',
            field=models.CharField(max_length=50, null=True, verbose_name='Marca del Producto'),
        ),
    ]
