# Generated by Django 4.0.4 on 2022-06-27 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto_marca_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Socio',
        ),
        migrations.DeleteModel(
            name='Socio',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
